// Code generated by "stringer -type=EAPI"; DO NOT EDIT.

package apiresponse

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EAPIError-0]
	_ = x[EAPIMFARequired-1]
	_ = x[EAPIInvalidCredentials-2]
	_ = x[EAPIPathNotFound-3]
	_ = x[EAPIFieldValidation-4]
	_ = x[EAPIPasswordResetFail-5]
	_ = x[EAPIJSONBad-6]
	_ = x[EAPIDenied-7]
	_ = x[EIAMError-8]
}

const _EAPI_name = "EAPIErrorEAPIMFARequiredEAPIInvalidCredentialsEAPIPathNotFoundEAPIFieldValidationEAPIPasswordResetFailEAPIJSONBadEAPIDeniedEIAMError"

var _EAPI_index = [...]uint8{0, 9, 24, 46, 62, 81, 102, 113, 123, 132}

func (i EAPI) String() string {
	if i < 0 || i >= EAPI(len(_EAPI_index)-1) {
		return "EAPI(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EAPI_name[_EAPI_index[i]:_EAPI_index[i+1]]
}
